# Generated by Django 5.1.3 on 2024-11-19 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField()),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_history', to='mcq.question')),
            ],
        ),
    ]
