# Generated by Django 5.1.3 on 2024-11-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0003_alter_practicehistory_submitted_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='practicehistory',
            table='mcq_practice_histories',
        ),
    ]
